/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as MenuPlansIndexRouteImport } from './routes/menu-plans.index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients.index'
import { Route as RecipesUpdateRouteImport } from './routes/recipes.update'
import { Route as RecipesNewRouteImport } from './routes/recipes.new'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'
import { Route as MenuPlansNewRouteImport } from './routes/menu-plans.new'
import { Route as MenuPlansMenuPlanIdRouteImport } from './routes/menu-plans.$menuPlanId'
import { Route as IngredientsNewRouteImport } from './routes/ingredients.new'
import { Route as IngredientsIngredientIdRouteImport } from './routes/ingredients.$ingredientId'
import { Route as RecipesRecipeIdUpdateRouteImport } from './routes/recipes_.$recipeId.update'
import { Route as MenuPlansMenuPlanIdUpdateRouteImport } from './routes/menu-plans_.$menuPlanId.update'
import { Route as IngredientsIngredientIdUpdateRouteImport } from './routes/ingredients_.$ingredientId.update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuPlansIndexRoute = MenuPlansIndexRouteImport.update({
  id: '/menu-plans/',
  path: '/menu-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesUpdateRoute = RecipesUpdateRouteImport.update({
  id: '/recipes/update',
  path: '/recipes/update',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuPlansNewRoute = MenuPlansNewRouteImport.update({
  id: '/menu-plans/new',
  path: '/menu-plans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuPlansMenuPlanIdRoute = MenuPlansMenuPlanIdRouteImport.update({
  id: '/menu-plans/$menuPlanId',
  path: '/menu-plans/$menuPlanId',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientIdRoute = IngredientsIngredientIdRouteImport.update({
  id: '/ingredients/$ingredientId',
  path: '/ingredients/$ingredientId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdUpdateRoute = RecipesRecipeIdUpdateRouteImport.update({
  id: '/recipes_/$recipeId/update',
  path: '/recipes/$recipeId/update',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuPlansMenuPlanIdUpdateRoute =
  MenuPlansMenuPlanIdUpdateRouteImport.update({
    id: '/menu-plans_/$menuPlanId/update',
    path: '/menu-plans/$menuPlanId/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const IngredientsIngredientIdUpdateRoute =
  IngredientsIngredientIdUpdateRouteImport.update({
    id: '/ingredients_/$ingredientId/update',
    path: '/ingredients/$ingredientId/update',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/menu-plans/$menuPlanId': typeof MenuPlansMenuPlanIdRoute
  '/menu-plans/new': typeof MenuPlansNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/update': typeof RecipesUpdateRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/menu-plans/': typeof MenuPlansIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/ingredients/$ingredientId/update': typeof IngredientsIngredientIdUpdateRoute
  '/menu-plans/$menuPlanId/update': typeof MenuPlansMenuPlanIdUpdateRoute
  '/recipes/$recipeId/update': typeof RecipesRecipeIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/menu-plans/$menuPlanId': typeof MenuPlansMenuPlanIdRoute
  '/menu-plans/new': typeof MenuPlansNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/update': typeof RecipesUpdateRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/menu-plans': typeof MenuPlansIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/ingredients/$ingredientId/update': typeof IngredientsIngredientIdUpdateRoute
  '/menu-plans/$menuPlanId/update': typeof MenuPlansMenuPlanIdUpdateRoute
  '/recipes/$recipeId/update': typeof RecipesRecipeIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/menu-plans/$menuPlanId': typeof MenuPlansMenuPlanIdRoute
  '/menu-plans/new': typeof MenuPlansNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/update': typeof RecipesUpdateRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/menu-plans/': typeof MenuPlansIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/ingredients_/$ingredientId/update': typeof IngredientsIngredientIdUpdateRoute
  '/menu-plans_/$menuPlanId/update': typeof MenuPlansMenuPlanIdUpdateRoute
  '/recipes_/$recipeId/update': typeof RecipesRecipeIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingredients/$ingredientId'
    | '/ingredients/new'
    | '/menu-plans/$menuPlanId'
    | '/menu-plans/new'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/update'
    | '/ingredients/'
    | '/menu-plans/'
    | '/recipes/'
    | '/ingredients/$ingredientId/update'
    | '/menu-plans/$menuPlanId/update'
    | '/recipes/$recipeId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingredients/$ingredientId'
    | '/ingredients/new'
    | '/menu-plans/$menuPlanId'
    | '/menu-plans/new'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/update'
    | '/ingredients'
    | '/menu-plans'
    | '/recipes'
    | '/ingredients/$ingredientId/update'
    | '/menu-plans/$menuPlanId/update'
    | '/recipes/$recipeId/update'
  id:
    | '__root__'
    | '/'
    | '/ingredients/$ingredientId'
    | '/ingredients/new'
    | '/menu-plans/$menuPlanId'
    | '/menu-plans/new'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/update'
    | '/ingredients/'
    | '/menu-plans/'
    | '/recipes/'
    | '/ingredients_/$ingredientId/update'
    | '/menu-plans_/$menuPlanId/update'
    | '/recipes_/$recipeId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngredientsIngredientIdRoute: typeof IngredientsIngredientIdRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  MenuPlansMenuPlanIdRoute: typeof MenuPlansMenuPlanIdRoute
  MenuPlansNewRoute: typeof MenuPlansNewRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesUpdateRoute: typeof RecipesUpdateRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  MenuPlansIndexRoute: typeof MenuPlansIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  IngredientsIngredientIdUpdateRoute: typeof IngredientsIngredientIdUpdateRoute
  MenuPlansMenuPlanIdUpdateRoute: typeof MenuPlansMenuPlanIdUpdateRoute
  RecipesRecipeIdUpdateRoute: typeof RecipesRecipeIdUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-plans/': {
      id: '/menu-plans/'
      path: '/menu-plans'
      fullPath: '/menu-plans/'
      preLoaderRoute: typeof MenuPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/update': {
      id: '/recipes/update'
      path: '/recipes/update'
      fullPath: '/recipes/update'
      preLoaderRoute: typeof RecipesUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-plans/new': {
      id: '/menu-plans/new'
      path: '/menu-plans/new'
      fullPath: '/menu-plans/new'
      preLoaderRoute: typeof MenuPlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-plans/$menuPlanId': {
      id: '/menu-plans/$menuPlanId'
      path: '/menu-plans/$menuPlanId'
      fullPath: '/menu-plans/$menuPlanId'
      preLoaderRoute: typeof MenuPlansMenuPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientId': {
      id: '/ingredients/$ingredientId'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId'
      preLoaderRoute: typeof IngredientsIngredientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes_/$recipeId/update': {
      id: '/recipes_/$recipeId/update'
      path: '/recipes/$recipeId/update'
      fullPath: '/recipes/$recipeId/update'
      preLoaderRoute: typeof RecipesRecipeIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-plans_/$menuPlanId/update': {
      id: '/menu-plans_/$menuPlanId/update'
      path: '/menu-plans/$menuPlanId/update'
      fullPath: '/menu-plans/$menuPlanId/update'
      preLoaderRoute: typeof MenuPlansMenuPlanIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients_/$ingredientId/update': {
      id: '/ingredients_/$ingredientId/update'
      path: '/ingredients/$ingredientId/update'
      fullPath: '/ingredients/$ingredientId/update'
      preLoaderRoute: typeof IngredientsIngredientIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngredientsIngredientIdRoute: IngredientsIngredientIdRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  MenuPlansMenuPlanIdRoute: MenuPlansMenuPlanIdRoute,
  MenuPlansNewRoute: MenuPlansNewRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesNewRoute: RecipesNewRoute,
  RecipesUpdateRoute: RecipesUpdateRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  MenuPlansIndexRoute: MenuPlansIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  IngredientsIngredientIdUpdateRoute: IngredientsIngredientIdUpdateRoute,
  MenuPlansMenuPlanIdUpdateRoute: MenuPlansMenuPlanIdUpdateRoute,
  RecipesRecipeIdUpdateRoute: RecipesRecipeIdUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
